version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_ceramic_cups
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./ecommerce_ceramic_cups.sql:/docker-entrypoint-initdb.d/ecommerce_ceramic_cups.sql
    ports:
      - '3306:3306'

  # Redis Cache Service
  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    command: ['redis-server', '--requirepass', 'mysecretpassword']
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672' # AMQP protocol port
      - '15672:15672' # RabbitMQ management dashboard

volumes:
  mysql_data:
  redis_data:
